// SSHCustom companion app — root-aware Compose UI for /api/v1/*
//
// Decisions captured in .kiro/steering/v2-roadmap.md:
//   - Hybrid: native Compose for Home/Profiles/Settings, WebView for Logs
//   - Min SDK 26, target SDK 35
//   - Material You (API 31+) with fixed-palette fallback below
//   - libsu for root command execution
//   - Package id permanent: com.sshcustom.app
//
// The release keystore is generated by CI (PR 5) and stored in repo Secrets;
// debug builds use the standard Android debug keystore so contributors can
// build locally without owning the signing key.

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "com.sshcustom.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.sshcustom.app"
        minSdk = 26
        targetSdk = 35

        // versionCode and versionName are injected from the repo VERSION file
        // via the buildscript block at the bottom. Bumping VERSION updates
        // module.prop, the Go binary, and the APK in lockstep.
        versionCode = rootProject.extra["sshcVersionCode"] as Int
        versionName = rootProject.extra["sshcVersion"] as String

        vectorDrawables { useSupportLibrary = true }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // signingConfig wired in PR 5 from CI secrets
        }
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    compileOptions {
        // Java 17 — Android Gradle Plugin 8.x requires it; widely available
        // on dev machines and matches what GitHub Actions ships with.
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "/META-INF/INDEX.LIST",
                "/META-INF/io.netty.versions.properties",
            )
        }
    }
}

dependencies {
    // Compose BOM keeps Material3 + UI artifacts on a single coordinated version
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.material.views)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.webkit)
    implementation(libs.androidx.datastore.preferences)

    // libsu for root shell access. The companion app needs root to call
    // /data/adb/sshcustom/sshcustom.sh (start/stop/restart) and to read
    // /data/adb/sshcustom/profiles.json when the daemon is offline.
    // Topjohnwu's libsu is the industry-standard wrapper used by Magisk
    // Manager itself, so KSU-Next, Shamiko, and most root apps already use it.
    implementation(libs.libsu.core)

    // Networking. OkHttp + kotlinx-serialization is much lighter than
    // Retrofit + Moshi for our 14-endpoint surface, and SSE support is
    // straightforward via okhttp-sse.
    implementation(libs.okhttp)
    implementation(libs.okhttp.sse)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.android)

    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
}
